name: Webhook invokable scheduler
on:
  repository_dispatch:
    types: [schedule-appointment]
jobs:
  run:
    runs-on: macos-11
    env:
      APP_TOKEN: ${{ secrets.APP_TOKEN }}
      APP_URL: ${{ secrets.APP_URL }}
      CONFIRMATION_TEXT: ${{ secrets.CONFIRMATION_TEXT }}
      LOGIN_PAGE: ${{ secrets.LOGIN_PAGE }}
      PASSWORD: ${{ secrets.PASSWORD }}
      SCHEDULE_BUTTON_SELECTOR: ${{ secrets.SCHEDULE_BUTTON_SELECTOR }}
      USERNAME: ${{ secrets.USERNAME }}
    name: Schedule Appointment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Schedule the appointment
        run: ./ci/schedule-time.sh ${{ github.event.client_payload.date }} ${{ github.event.client_payload.time }}